window.EV_CHARGER_COUNTRIES = [
  "Afghanistan",
  "Aland Islands",
  "Albania",
  "Andorra",
  "Argentina",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Barbados",
  "Belarus",
  "Belgium",
  "Bermuda",
  "Bosnia And Herzegovina",
  "Brazil",
  "British Indian Ocean Territory",
  "Bulgaria",
  "Cambodia",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Costa Rica",
  "Croatia",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "Estonia",
  "Faroe Islands",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Guernsey",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Ireland",
  "Isle Of Man",
  "Israel",
  "Italy",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Latvia",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Macedonia",
  "Malaysia",
  "Mali",
  "Malta",
  "Mauritius",
  "Mexico",
  "Moldova, Republic Of",
  "Monaco",
  "Montenegro",
  "Morocco",
  "Namibia",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Norway",
  "Pakistan",
  "Palestinian Territory, Occupied",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Reunion",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Lucia",
  "San Marino",
  "Serbia",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "Spain",
  "Sri Lanka",
  "Suriname",
  "Svalbard And Jan Mayen",
  "Sweden",
  "Switzerland",
  "Taiwan, Province Of China",
  "Thailand",
  "Trinidad And Tobago",
  "Tunisia",
  "Turkey",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uzbekistan",
  "Vanuatu",
  "Virgin Islands, U.S.",
  "Yemen"
];
